### ISSUE TITLE
Error: Unable to locate executable file: cachix.

### ISSUE THREAD

**Issue by rvolosatovs** [cachix/cachix-action#138]
A few minutes ago, all `cachix/cachix-action@v12` jobs started to fail with:
```  
Error: Action failed with error: Error: Unable to locate executable file: cachix. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

E.g. https://github.com/rvolosatovs/wash/actions/runs/4295788214/jobs/7486677553

**Comment by rsdy** [comment]
I'm seeing the same thing.

**Comment by ehildenb** [comment]
We're seeing the same thing.

**Comment by rvolosatovs** [comment]
> This is not an issue with this action. The latest nix release (2.14.0) has a regression which causes this.
> 
> Pinning nix version in the nix-install-action resolves it:
> 
> ```
> install_url: https://releases.nixos.org/nix/nix-2.13.3/install
> ```
> 
> See [NixOS/nixpkgs#218858 (comment)](https://github.com/NixOS/nixpkgs/pull/218858#issuecomment-1448758169)

Thank you! This solved my issue, closing

**Comment by dpc** [comment]
I see the same thing on a self-hosted macos runner and I don't even know why. How does one debug this?

**Comment by sandydoo** [comment]
> I see the same thing on a self-hosted macos runner and I don't even know why. How does one debug this?

This usually means that we can't find the cachix executable in your PATH. You can start tracking this down by echo-ing PATH during the workflow and making sure the it contains paths to the system/user profiles.
I would recommend pre-installing cachix if using a self-hosted runner.

**Comment by dpc** [comment]
I forgot to post an update. I fixed it couple of hours after posting.

This was caused by GH action runner wiping the environment on start, discarding Nix environment. It's weird because it works fine on Linux, in similar setup. I think it's because shell is not being used to invoke commands on MacOS, while it is on Linux, or because DeterminateSystems installer is wiring things up differently between the two for some reason.

The fix was to run `./env.sh` after sourcing Nix init script to update `.env` and `.path` inside the runner's dir.
