### ISSUE TITLE
Why is cachix installed from a nixpkgs snapshot?

### ISSUE THREAD

**Issue by abbec** [cachix/cachix-action#41]
I saw that https://cachix.org/api/v1/install is essentially a snapshot of nixpkgs. Seems like if you use this action in combination with the `install-nix` action you could install cachix with `nix-env -iA nixpkgs.cachix` and save ~20 seconds of unpacking the aforementioned snapshot since it is already in nixpkgs.

Am I missing something?

**Comment by domenkozar** [comment]
That way I have control which version of cachix gets installed in different environments. I'm doing my best to keep version in nixpkgs up to date, but it's not always easy (for reasons that Haskell package set gets updates on rolling and best effort case).

On top of that many things can go wrong, for example closure size going up suddenly because of some unrelated Haskell packaging change.

I am thinking of doing binary distribution for linux & aarch64 & macos that would solve this for almost all users.

That would save the same amount of installation time and keep the control of stable and known to work versions.

**Comment by abbec** [comment]
Ah, ok that makes sense, I will close this then since it was more of a question. Will you open another issue I can follow for the binary distribution?

Also, thanks for a great service! :)

**Comment by domenkozar** [comment]
Best to follow https://github.com/cachix/cachix/issues/184
