### ISSUE TITLE
New packages are not being pushed to cache, when using GitHub Actions

### ISSUE THREAD

**Issue by srid** [cachix/cachix-action#54]
In the neuron project, a PR just got merged that introduced changes to some dependencies: https://github.com/srid/neuron/pull/315

Per the [action run](https://github.com/srid/neuron/runs/932846066#step:23:39), cachix did seem to push the new ones (notably pandoc, but also skylighting) as one would expect.

However, once the PR got merged to master in https://github.com/srid/neuron/commit/76fc3e4a3221f16767b1dce60c92b790a66e7de9 - the new binaries from cache were not used; and they were rebuilding again.

The same issue happens on subsequent commits on `master`, such as this one https://github.com/srid/neuron/commit/0b15fdf2a65eccb257423192eb248bfb8eb915a3 - and as you can see the build took over 30 mins, building pandoc and friends.

It looks like the `cachix push` step of the action did not really push all the binaries. That or, something has gone wrong in the cachix server?

**Comment by domenkozar** [comment]
Hey @srid, this was fixed yesterday. There was a bug with upstream caches, since Cachix verifies that it has the full closure before it serves the narinfo (due to a Nix bug) and with upstream caches it doesn't have the full closure. So now the exception for those is added and everything should be back to working.
