### ISSUE TITLE
Any way to disable pushing of tiny deriviations?

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [cachix/cachix-action#70]
The easy way of implementing something like that would be to tweak `push-paths.sh` script to list paths with human-readable size and drop those lines that do not end with K, M, G
Admittedly this kind of implementation does not sound great but I'd love to see such feature implemented.

**Comment by domenkozar** [comment]
What is the use case?

You can set `allowSubstitutes = false` on derivations to prevent them being downloaded, so Cachix should probably respect that also when pushing. 

In general that's useful when the build is more trivial (takes less time) than pushing and pulling.

A tiny derivation could take a long time to build, since there's no direct correlation between the output size and build time.

**Comment by gytis-ivaskevicius** [comment]
Use case:
I have a GitHub action setup for my system config - it pushes these tiny files like in a screenshot below which are a little annoying to look at :D . 
Also, I got a feeling that it would be just faster to build em on the go instead.
![image](https://user-images.githubusercontent.com/23264966/99788272-8e8a1680-2b29-11eb-9c41-5259946f27bc.png)

**Comment by domenkozar** [comment]
Can't think of any reasonable way to make this work. Even if you filter out paths, if they are a dependency of any other path, they will be uploaded otherwise binary caches break. So your NixOS root path will include these. 

And if I add this feature it can't be relied on, because of reasons above.

I think a better way forward is to pick compression algorithm that is less CPU intensive than xz.

**Comment by gytis-ivaskevicius** [comment]
I understand. I guess this issue should be closed?
