### ISSUE TITLE
Cache is not used

### ISSUE THREAD

**Issue by vrom911** [cachix/cachix-action#9]
I followed the instructions and created my cache named `vrom911.cachix.org`.

And here is the CI config I'm using: https://github.com/vrom911/haskeller-answers/blob/b31f221bbc3a671ac15bb42b0da52872a4070197/.github/workflows/ci.yml

Though, it started to build everything from the start for a minor PR:
* https://github.com/vrom911/haskeller-answers/pull/18

My profile on `cachix` says that some cache was created as I have non-zero storage size now and I'm not using it in any other places at the moment.

This is particularly strange because we are using similar config for the @kowainik repos and it works smoothly. Could you advise what can be done?

P.S. thanks for putting this project up together :+1:

**Comment by domenkozar** [comment]
Hey @vrom911, glad to see you using cachix :)

This is a combination of two issues:

a) Use of [./.](https://github.com/vrom911/haskeller-answers/blob/master/default.nix#L9) that pulls in everything for a rebuild
b) cachix is caching only the runtime closure, there are [workarounds described in cachix issue tracker, but none are simple](https://github.com/cachix/cachix/issues/9)

For a) I recommend using filters to filter out the things that won't affect the build. There's no best way to do that with Haskell (there are some sdist commands, would need to play with that) as far as I'm aware.

For b) this really should be fixed in cachix, but you can try the workaround (although that won't work until cachix-action allows overriding the build command).

**Comment by vrom911** [comment]
Thank you for the quick response!

This clarifies things for me. I'll try to see how I could handle this. But feel free to close this issue, if you think that mentioned one would be enough for the problem :slightly_smiling_face:
